deeplob:
  batch_size: 32
  learning_rate: 0.01
  epsilon: 1e-08
  epoch: 30
  num_workers: 4

deeplob-lighten:
  batch_size: 128
  learning_rate: 0.001
  epsilon: 1e-08
  epoch: 30
  num_workers: 4

lobster:
  batch_size: 32
  learning_rate: 0.01
  epsilon: 1e-08
  epoch: 30
  num_workers: 4

lobster-light:
  batch_size: 32
  learning_rate: 0.01
  epsilon: 1e-08
  epoch: 30
  num_workers: 4