deeplob:
  batch_size: 64
  learning_rate: 0.01
  epsilon: 1
  epoch: 10
  num_workers: 4

deeplob-lighten:
  batch_size: 64
  learning_rate: 0.01
  epsilon: 1
  epoch: 10
  num_workers: 4

lobster:
  batch_size: 64
  learning_rate: 0.01
  epsilon: 1
  epoch: 10
  num_workers: 4

lobster-light:
  batch_size: 64
  learning_rate: 0.01
  epsilon: 1
  epoch: 10
  num_workers: 4